"""
Django settings for gestor_seguros project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
import sys,dj_database_url
from pathlib import Path
from dotenv import load_dotenv  

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%$9b3nwa0_vy9($qfp*37%mk2hg)a&w!6$23$#-hwna!xvrw9z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost','gestorseguro-production.up.railway.app','127.0.0.1']

CSRF_TRUSTED_ORIGINS = ["http://*",'https://gestorseguro-production.up.railway.app']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cuentas', # Nueva app
    'widget_tweaks',
    'crispy_forms',  # Para formularios más bonitos
    'crispy_bootstrap5',  # Para usar Bootstrap 5 con crispy_forms
    'clientes',
    'polizas',
    'django.contrib.humanize',
    'documentos',
    'reportes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gestor_seguros.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], # Añade esto
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gestor_seguros.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default':dj_database_url.config(default= os.getenv('DATABASE_URL')),
}   


# --- SECCIÓN DE BASE DE DATOS ---

# Intentar obtener la URL de la base de datos de producción (Railway)
#db_from_env = os.getenv('DATABASE_URL')

#if db_from_env:
    # Opción REMOTA (PRODUCCIÓN/RAILWAY)
    #print("Usando Base de Datos Remota (PostgreSQL)")
    
    # Usamos dj_database_url para parsear la URL de Railway
    #DATABASES = {
        #'default': dj_database_url.config(
#            default=db_from_env,
#            conn_max_age=600  # Opcional
#  )
#}

#else:
#   # Opción LOCAL (DESARROLLO/SQLite)
#    # ESTA SECCIÓN SE EJECUTA SI NO SE ENCUENTRA DATABASE_URL en el entorno local
#   print("Usando Base de Datos Local (SQLite)")
#    DATABASES = {
#       'default': {
#          'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}
    
# -----------------------------------



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

#Establece la zona horaria de Venezuela. Esta es la clave.
TIME_ZONE = 'America/Caracas'
# Mantenemos la internacionalización activa por si la necesitas en el futuro.
USE_I18N = True

# Esto hará que Django use formatos estándar (ej. punto para decimales, YYYY-MM-DD para inputs).
USE_L10N = False # <-- CAMBIO CRÍTICO

# 5. Mantenemos el soporte de zonas horarias activo.
USE_TZ = True


LOGIN_URL = 'login' # La URL donde está tu página de login
LOGIN_REDIRECT_URL = 'dashboard' # A DÓNDE IR DESPUÉS DE UN LOGIN EXITOSO
LOGOUT_REDIRECT_URL = 'pagina_inicio' # A dónde ir después de cerrar sesión

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') 
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'







