# Generated by Django 4.2.7 on 2026-03-10 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_agencia', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre de la Agencia')),
                ('rif', models.CharField(blank=True, max_length=50, null=True, verbose_name='RIF/Identificación Fiscal')),
                ('telefono_profesional', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Profesional')),
                ('direccion_agencia', models.TextField(blank=True, null=True, verbose_name='Dirección de la Agencia')),
                ('biografia', models.TextField(blank=True, null=True, verbose_name='Breve Biografía/Descripción')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
