# Generated by Django 4.2.7 on 2025-10-21 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aseguradora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre de la Aseguradora')),
                ('nit', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='NIT')),
                ('contacto_nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de Contacto')),
                ('contacto_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de Contacto')),
                ('contacto_telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de Contacto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aseguradoras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aseguradora',
                'verbose_name_plural': 'Aseguradoras',
                'ordering': ['nombre'],
                'unique_together': {('usuario', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_poliza', models.CharField(max_length=100, unique=True, verbose_name='Número de Póliza')),
                ('ramo_tipo_seguro', models.CharField(max_length=100, verbose_name='Ramo o Tipo de Seguro (Ej: Vida, Auto, Hogar)')),
                ('descripcion_bien_asegurado', models.TextField(blank=True, null=True, verbose_name='Descripción del Bien Asegurado (Ej: Placa Vehículo, Dirección Inmueble)')),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Emisión')),
                ('fecha_inicio_vigencia', models.DateField(verbose_name='Fecha Inicio de Vigencia')),
                ('fecha_fin_vigencia', models.DateField(verbose_name='Fecha Fin de Vigencia')),
                ('prima_total_anual', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prima Total Anual/Valor Asegurado')),
                ('frecuencia_pago', models.CharField(choices=[('MENSUAL', 'Mensual'), ('TRIMESTRAL', 'Trimestral'), ('CUATRIMESTRAL', 'Cuatrimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual'), ('UNICO', 'Pago Único')], default='ANUAL', max_length=15, verbose_name='Frecuencia de Pago/Renovación')),
                ('valor_cuota', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Cuota (si aplica)')),
                ('comision_monto', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto de Comisión')),
                ('comision_cobrada', models.BooleanField(default=False, verbose_name='¿Comisión Cobrada?')),
                ('fecha_cobro_comision', models.DateField(blank=True, null=True, verbose_name='Fecha Cobro Comisión')),
                ('estado_poliza', models.CharField(choices=[('VIGENTE', 'Vigente'), ('PENDIENTE_PAGO', 'Pendiente de Pago'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada'), ('EN_TRAMITE', 'En Trámite')], default='EN_TRAMITE', max_length=20, verbose_name='Estado de la Póliza')),
                ('notas_poliza', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales de la Póliza')),
                ('archivo_poliza', models.FileField(blank=True, null=True, upload_to='polizas_archivos/', verbose_name='Archivo de la Póliza (PDF)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('aseguradora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polizas', to='polizas.aseguradora', verbose_name='Aseguradora')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polizas', to='clientes.cliente', verbose_name='Cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polizas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Póliza',
                'verbose_name_plural': 'Pólizas',
                'ordering': ['-fecha_fin_vigencia', 'cliente'],
                'unique_together': {('usuario', 'numero_poliza')},
            },
        ),
    ]
