# Generated by Django 4.2.7 on 2025-11-07 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0003_alter_cliente_tipo_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aseguradora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre de la Aseguradora')),
                ('rif', models.CharField(blank=True, max_length=20, null=True, verbose_name='RIF')),
                ('contacto_nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de Contacto')),
                ('contacto_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de Contacto')),
                ('contacto_telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de Contacto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aseguradoras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aseguradora',
                'verbose_name_plural': 'Aseguradoras',
                'ordering': ['nombre'],
                'unique_together': {('usuario', 'rif')},
            },
        ),
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_poliza', models.CharField(max_length=100, unique=True, verbose_name='Número de Póliza')),
                ('ramo_tipo_seguro', models.CharField(max_length=100, verbose_name='Ramo o Tipo de Seguro (Ej: Vida, Auto, Hogar)')),
                ('descripcion_bien_asegurado', models.TextField(blank=True, null=True, verbose_name='Descripción del Bien Asegurado (Ej: Placa Vehículo, Dirección Inmueble)')),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Emisión')),
                ('fecha_inicio_vigencia', models.DateField(verbose_name='Fecha Inicio de Vigencia')),
                ('fecha_fin_vigencia', models.DateField(verbose_name='Fecha Fin de Vigencia')),
                ('prima_total_anual', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prima Total Anual/Valor Asegurado')),
                ('frecuencia_pago', models.CharField(choices=[('UNICO', 'Pago Único'), ('MENSUAL', 'Mensual'), ('TRIMESTRAL', 'Trimestral'), ('CUATRIMESTRAL', 'Cuatrimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], default='ANUAL', max_length=15, verbose_name='Frecuencia de Pago de Cuotas')),
                ('valor_cuota', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Cuota (si aplica)')),
                ('comision_monto', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto de Comisión')),
                ('comision_cobrada', models.BooleanField(default=False, verbose_name='¿Comisión Cobrada?')),
                ('fecha_cobro_comision', models.DateField(blank=True, null=True, verbose_name='Fecha Cobro Comisión')),
                ('estado_poliza', models.CharField(choices=[('VIGENTE', 'Vigente'), ('PENDIENTE_PAGO', 'Pendiente de Pago'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada'), ('EN_TRAMITE', 'En Trámite'), ('RENOVADA', 'Renovada')], default='EN_TRAMITE', max_length=20, verbose_name='Estado de la Póliza')),
                ('notas_poliza', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales de la Póliza')),
                ('archivo_poliza', models.FileField(blank=True, null=True, upload_to='polizas_archivos/', verbose_name='Archivo de la Póliza (PDF)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('aseguradora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polizas', to='polizas.aseguradora', verbose_name='Aseguradora')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polizas', to='clientes.cliente', verbose_name='Cliente')),
                ('renovacion_de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renovaciones', to='polizas.poliza', verbose_name='Es renovación de')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polizas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Póliza',
                'verbose_name_plural': 'Pólizas',
                'ordering': ['-fecha_fin_vigencia', 'cliente'],
                'unique_together': {('usuario', 'numero_poliza', 'fecha_inicio_vigencia')},
            },
        ),
        migrations.CreateModel(
            name='Siniestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ocurrencia', models.DateField(verbose_name='Fecha de Ocurrencia')),
                ('fecha_reporte', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Reporte')),
                ('estado_siniestro', models.CharField(choices=[('REPORTADO', 'Reportado'), ('EN_ANALISIS', 'En Análisis'), ('PERDIDA_TOTAL', 'Pérdida Total'), ('PAGADO', 'Pagado / Indemnizado'), ('RECHAZADO', 'Rechazado'), ('CERRADO', 'Cerrado')], default='REPORTADO', max_length=20, verbose_name='Estado del Siniestro')),
                ('descripcion', models.TextField(verbose_name='Descripción del Siniestro')),
                ('monto_reclamado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto Reclamado')),
                ('monto_indemnizado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto Indemnizado/Pagado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siniestros', to='polizas.poliza')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siniestros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Siniestro',
                'verbose_name_plural': 'Siniestros',
                'ordering': ['-fecha_ocurrencia'],
            },
        ),
        migrations.CreateModel(
            name='PagoCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vencimiento_cuota', models.DateField(verbose_name='Fecha de Vencimiento de la Cuota')),
                ('monto_cuota', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto de la Cuota')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('VENCIDO', 'Vencido')], default='PENDIENTE', max_length=10)),
                ('fecha_de_pago_realizado', models.DateField(blank=True, null=True, verbose_name='Fecha en que se pagó')),
                ('notas_pago', models.TextField(blank=True, null=True, verbose_name='Notas del pago')),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='polizas.poliza')),
            ],
            options={
                'verbose_name': 'Cuota de Póliza',
                'verbose_name_plural': 'Cuotas de Póliza',
                'ordering': ['fecha_vencimiento_cuota'],
            },
        ),
        migrations.CreateModel(
            name='Asegurado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre Completo del Asegurado')),
                ('cedula', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cédula / RIF')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('parentesco', models.CharField(blank=True, choices=[('TITULAR', 'Titular'), ('CONYUGE', 'Cónyuge'), ('HIJO_A', 'Hijo/a'), ('PADRE_MADRE', 'Padre/Madre'), ('OTRO', 'Otro')], max_length=20, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True, verbose_name='Sexo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email del Asegurado')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del Asegurado')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas sobre el Asegurado')),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asegurados', to='polizas.poliza')),
            ],
            options={
                'verbose_name': 'Asegurado en Póliza',
                'verbose_name_plural': 'Asegurados en Póliza',
                'ordering': ['parentesco', 'nombre_completo'],
            },
        ),
    ]
