# Generated by Django 4.2.7 on 2025-11-06 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polizas', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='poliza',
            unique_together={('usuario', 'numero_poliza', 'fecha_inicio_vigencia')},
        ),
        migrations.AddField(
            model_name='poliza',
            name='renovacion_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renovaciones', to='polizas.poliza', verbose_name='Es renovación de'),
        ),
    ]
