# Generated by Django 5.2.8 on 2026-03-09 21:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aseguradora',
            unique_together={('usuario', 'rif')},
        ),
        migrations.AlterField(
            model_name='aseguradora',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre de la Aseguradora'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='numero_poliza',
            field=models.CharField(max_length=100, verbose_name='Número de Póliza'),
        ),
        migrations.AlterUniqueTogether(
            name='aseguradora',
            unique_together={('usuario', 'nombre'), ('usuario', 'rif')},
        ),
    ]
