# Generated by Django 4.2.7 on 2025-10-29 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='ultimo_pago_cubierto_hasta',
            field=models.DateField(blank=True, help_text='Indica la fecha final del período cubierto por el último pago realizado.', null=True, verbose_name='Último pago cubre hasta'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='estado_poliza',
            field=models.CharField(choices=[('VIGENTE', 'Vigente'), ('PENDIENTE_PAGO', 'Pendiente de Pago'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada'), ('EN_TRAMITE', 'En Trámite'), ('PAGADA', 'Pagada'), ('RENOVADA', 'Renovada')], default='EN_TRAMITE', max_length=20, verbose_name='Estado de la Póliza'),
        ),
    ]
