# Generated by Django 4.2.7 on 2026-03-10 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_historicalcliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polizas', '0002_alter_aseguradora_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPoliza',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('numero_poliza', models.CharField(max_length=100, verbose_name='Número de Póliza')),
                ('ramo_tipo_seguro', models.CharField(max_length=100, verbose_name='Ramo o Tipo de Seguro (Ej: Vida, Auto, Hogar)')),
                ('descripcion_bien_asegurado', models.TextField(blank=True, null=True, verbose_name='Descripción del Bien Asegurado (Ej: Placa Vehículo, Dirección Inmueble)')),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Emisión')),
                ('fecha_inicio_vigencia', models.DateField(verbose_name='Fecha Inicio de Vigencia')),
                ('fecha_fin_vigencia', models.DateField(verbose_name='Fecha Fin de Vigencia')),
                ('prima_total_anual', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prima Total Anual/Valor Asegurado')),
                ('frecuencia_pago', models.CharField(choices=[('UNICO', 'Pago Único'), ('MENSUAL', 'Mensual'), ('TRIMESTRAL', 'Trimestral'), ('CUATRIMESTRAL', 'Cuatrimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], default='ANUAL', max_length=15, verbose_name='Frecuencia de Pago de Cuotas')),
                ('valor_cuota', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Cuota (si aplica)')),
                ('comision_monto', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto de Comisión')),
                ('comision_cobrada', models.BooleanField(default=False, verbose_name='¿Comisión Cobrada?')),
                ('fecha_cobro_comision', models.DateField(blank=True, null=True, verbose_name='Fecha Cobro Comisión')),
                ('estado_poliza', models.CharField(choices=[('VIGENTE', 'Vigente'), ('PENDIENTE_PAGO', 'Pendiente de Pago'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada'), ('EN_TRAMITE', 'En Trámite'), ('RENOVADA', 'Renovada')], default='EN_TRAMITE', max_length=20, verbose_name='Estado de la Póliza')),
                ('notas_poliza', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales de la Póliza')),
                ('archivo_poliza', models.TextField(blank=True, max_length=100, null=True, verbose_name='Archivo de la Póliza (PDF)')),
                ('fecha_creacion', models.DateTimeField(blank=True, editable=False)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('aseguradora', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='polizas.aseguradora', verbose_name='Aseguradora')),
                ('cliente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clientes.cliente', verbose_name='Cliente')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('renovacion_de', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='polizas.poliza', verbose_name='Es renovación de')),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Póliza',
                'verbose_name_plural': 'historical Pólizas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAseguradora',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Aseguradora')),
                ('rif', models.CharField(blank=True, max_length=20, null=True, verbose_name='RIF')),
                ('contacto_nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de Contacto')),
                ('contacto_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de Contacto')),
                ('contacto_telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de Contacto')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Aseguradora',
                'verbose_name_plural': 'historical Aseguradoras',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
