# Generated by Django 4.2.7 on 2025-10-29 14:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0002_poliza_ultimo_pago_cubierto_hasta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poliza',
            name='ultimo_pago_cubierto_hasta',
        ),
        migrations.AlterField(
            model_name='poliza',
            name='estado_poliza',
            field=models.CharField(choices=[('VIGENTE', 'Vigente'), ('PENDIENTE_PAGO', 'Pendiente de Pago'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada'), ('EN_TRAMITE', 'En Trámite'), ('RENOVADA', 'Renovada')], default='EN_TRAMITE', max_length=20, verbose_name='Estado de la Póliza'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='frecuencia_pago',
            field=models.CharField(choices=[('UNICO', 'Pago Único'), ('MENSUAL', 'Mensual'), ('TRIMESTRAL', 'Trimestral'), ('CUATRIMESTRAL', 'Cuatrimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], default='ANUAL', max_length=15, verbose_name='Frecuencia de Pago de Cuotas'),
        ),
        migrations.CreateModel(
            name='PagoCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha en que se realizó el pago')),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Pagado')),
                ('fecha_cuota_correspondiente', models.DateField(verbose_name='Cuota correspondiente a la fecha')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas del pago')),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_cuotas', to='polizas.poliza')),
            ],
            options={
                'verbose_name': 'Pago de Cuota',
                'verbose_name_plural': 'Pagos de Cuotas',
                'ordering': ['-fecha_cuota_correspondiente'],
            },
        ),
    ]
