# Generated by Django 4.2.7 on 2025-10-29 16:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polizas', '0003_remove_poliza_ultimo_pago_cubierto_hasta_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aseguradora',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='aseguradora',
            name='rif',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RIF'),
        ),
        migrations.AlterUniqueTogether(
            name='aseguradora',
            unique_together={('usuario', 'rif')},
        ),
        migrations.RemoveField(
            model_name='aseguradora',
            name='nit',
        ),
    ]
