# Generated by Django 4.2.7 on 2025-10-30 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polizas', '0004_alter_aseguradora_unique_together_aseguradora_rif_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siniestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ocurrencia', models.DateField(verbose_name='Fecha de Ocurrencia')),
                ('fecha_reporte', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Reporte')),
                ('estado_siniestro', models.CharField(choices=[('REPORTADO', 'Reportado'), ('EN_ANALISIS', 'En Análisis'), ('PERDIDA_TOTAL', 'Pérdida Total'), ('PAGADO', 'Pagado / Indemnizado'), ('RECHAZADO', 'Rechazado'), ('CERRADO', 'Cerrado')], default='REPORTADO', max_length=20, verbose_name='Estado del Siniestro')),
                ('descripcion', models.TextField(verbose_name='Descripción del Siniestro')),
                ('monto_reclamado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto Reclamado')),
                ('monto_indemnizado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto Indemnizado/Pagado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siniestros', to='polizas.poliza')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siniestros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Siniestro',
                'verbose_name_plural': 'Siniestros',
                'ordering': ['-fecha_ocurrencia'],
            },
        ),
    ]
