# Generated by Django 4.2.7 on 2025-10-31 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0005_siniestro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asegurado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre Completo del Asegurado')),
                ('cedula', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cédula / RIF')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('parentesco', models.CharField(choices=[('TITULAR', 'Titular'), ('CONYUGE', 'Cónyuge'), ('HIJO_A', 'Hijo/a'), ('PADRE_MADRE', 'Padre/Madre'), ('OTRO', 'Otro')], default='TITULAR', max_length=20)),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asegurados', to='polizas.poliza')),
            ],
            options={
                'verbose_name': 'Asegurado en Póliza',
                'verbose_name_plural': 'Asegurados en Póliza',
                'ordering': ['parentesco', 'nombre_completo'],
            },
        ),
    ]
