# Generated by Django 4.2.7 on 2025-10-31 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0006_asegurado'),
    ]

    operations = [
        migrations.AddField(
            model_name='asegurado',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email del Asegurado'),
        ),
        migrations.AddField(
            model_name='asegurado',
            name='notas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas sobre el Asegurado'),
        ),
        migrations.AddField(
            model_name='asegurado',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='asegurado',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del Asegurado'),
        ),
    ]
