# Generated by Django 4.2.7 on 2025-10-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0007_asegurado_email_asegurado_notas_asegurado_sexo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asegurado',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre Completo del Asegurado'),
        ),
        migrations.AlterField(
            model_name='asegurado',
            name='parentesco',
            field=models.CharField(blank=True, choices=[('TITULAR', 'Titular'), ('CONYUGE', 'Cónyuge'), ('HIJO_A', 'Hijo/a'), ('PADRE_MADRE', 'Padre/Madre'), ('OTRO', 'Otro')], max_length=20, null=True),
        ),
    ]
