# Generated by Django 4.2.7 on 2025-10-22 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('NIT', 'NIT'), ('PAS', 'Pasaporte'), ('OTRO', 'Otro')], default='CC', max_length=5, verbose_name='Tipo de Documento')),
                ('numero_documento', models.CharField(max_length=50, unique=True, verbose_name='Número de Documento')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Correo Electrónico')),
                ('telefono_principal', models.CharField(max_length=20, verbose_name='Teléfono Principal')),
                ('telefono_secundario', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Secundario')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('profesion_ocupacion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Profesión/Ocupación')),
                ('notas_adicionales', models.TextField(blank=True, null=True, verbose_name='Notas Adicionales')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre_completo'],
                'unique_together': {('usuario', 'numero_documento')},
            },
        ),
    ]
