# Generated by Django 4.2.7 on 2025-10-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_telefono_principal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(choices=[('V', 'Cédula Venezolana (V)'), ('E', 'Cédula Extranjero (E)'), ('J', 'RIF Jurídico (J)'), ('G', 'RIF Gubernamental (G)'), ('P', 'Pasaporte')], default='V', max_length=5, verbose_name='Tipo de Documento'),
        ),
    ]
