# Generated by Django 5.0.3 on 2026-05-16 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_historicalcliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='historicalcliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
    ]
